-- Checking for already made database
DROP DATABASE IF EXISTS lol_database;

-- Checking for already made user
DROP USER IF EXISTS 'lol_user'@'localhost';

-- Creating database
CREATE DATABASE IF NOT EXISTS lol_database;

-- Creating user
CREATE USER IF NOT EXISTS 'lol_user'@'localhost' IDENTIFIED BY 'IFeedBotLane';

-- Granting permissions
GRANT SELECT, UPDATE, FILE ON *.* TO 'lol_user'@'localhost';

-- Switching to our database
USE lol_database;


-- Creating table for ADCs that work well with the Support.
CREATE TABLE IF NOT EXISTS SupportBottomPairing (
    Support VARCHAR(12) CHARACTER SET utf8,
    Bottom VARCHAR(12) CHARACTER SET utf8
);

-- Inserting values
INSERT INTO SupportBottomPairing (Support, Bottom) VALUES 
    ('Alistar','Caitlyn'),
	('Bard','Ezreal'),
	('Blitzcrank','Draven'),
	('Braum','Caitlyn'),
	('Janna','Tristana'),
	('Karma','Jhin'),
	('Leona','Draven'),
	('Lulu','Twitch'),
	('Lux','Miss Fortune'),
	('Maokai','Vayne'),
	('Milio','Kog''Maw'),
	('Morgana','Smolder'),
	('Nami','Lucian'),
	('Nautilus','Kai''Sa'),
	('Pyke','Jhin'),
	('Rakan','Xayah'),
	('Rell','Sivir'),
	('Renata Glasc','Kalista'),
	('Senna','Nilah'),
	('Sona','Varus'),
	('Soraka','Ashe'),
	('Taric','Aphelios'),
	('Thresh','Draven'),
	('Yuumi','N/A'),
	('Zilean','Zeri'),
	('Zyra','Sivir');


-- Creating Table for Champions
CREATE TABLE IF NOT EXISTS ChampionList (
    Champ VARCHAR(14) CHARACTER SET utf8,
    Pref_Role VARCHAR(7) CHARACTER SET utf8,
    Job VARCHAR(19) CHARACTER SET utf8,
    AP_AD VARCHAR(4) CHARACTER SET utf8
);

-- Inseting data for Champions
INSERT INTO ChampionList (Champ, Pref_Role, Job, AP_AD) VALUES 
    ('Aatrox','Top','Juggernaut','AD'),
	('Ahri','Middle','Burst','AP'),
	('Akali','Middle','Assassin','AP'),
	('Akshan','Middle','Assassin/Marksmen','AD'),
	('Alistar','Support','Vanguard','AD'),
	('Amumu','Jungle','Vanguard','AP'),
	('Anivia','Middle','Battlemage','AP'),
	('Annie','Middle','Burst','AP'),
	('Aphelios','Bottom','Marksmen','AD'),
	('Ashe','Bottom','Marksmen','AD'),
	('Aurelion Sol','Middle','Battlemage','AP'),
	('Azir','Middle','Specialist','AP'),
	('Bard','Support','Catcher','AP'),
	('Bel''Veth','Jungle','Skirmisher','AD'),
	('Blitzcrank','Support','Catcher','AD'),
	('Brand','Jungle','Burst','AP'),
	('Braum','Support','Warden','AD'),
	('Briar','Jungle','Diver','AD'),
	('Caitlyn','Bottom','Marksmen','AD'),
	('Camille','Top','Diver','AD'),
	('Cassiopeia','Middle','Battlemage','AP'),
	('Cho''Gath','Top','Specialist','AD'),
	('Corki','Middle','Marksmen','AD'),
	('Darius','Top','Juggernaut','AD'),
	('Diana','Jungle','Assassin/Diver','AP'),
	('Dr. Mundo','Top','Juggernaut','AD'),
	('Draven','Bottom','Marksmen','AD'),
	('Ekko','Middle','Assassin','AP'),
	('Elise','Jungle','Diver','AP'),
	('Evelynn','Jungle','Assassin','AP'),
	('Ezreal','Bottom','Marksmen','AD'),
	('Fiddlesticks','Jungle','Specialist','AP'),
	('Fiora','Top','Skirmisher','AD'),
	('Fizz','Middle','Assassin','AP'),
	('Galio','Middle','Warden','AP'),
	('Gangplank','Top','Specialist','AD'),
	('Garen','Top','Juggernaut','AD'),
	('Gnar','Top','Specialist','AD'),
	('Gragas','Jungle','Vanguard','AP'),
	('Graves','Jungle','Specialist','AD'),
	('Gwen','Top','Skirmisher','AP'),
	('Hecarim','Jungle','Diver','AD'),
	('Heimerdinger','Middle','Specialist','AP'),
	('Hwei','Middle','Artillery','AP'),
	('Illaoi','Top','Juggernaut','AD'),
	('Ivern','Jungle','Catcher','AP'),
	('Janna','Support','Enchanter','AP'),
	('Jarvan IV','Jungle','Diver','AD'),
	('Jax','Top','Skirmisher','AD'),
	('Jayce','Top','Artillery','AD'),
	('Jhin','Bottom','Marksmen/Catcher','AD'),
	('Jinx','Bottom','Marksmen','AD'),
	('Kai''Sa','Bottom','Marksmen','AP'),
	('Kalista','Bottom','Marksmen','AD'),
	('Karma','Support','Burst/Enchanter','AP'),
	('Karthus','Jungle','Battlemage','AP'),
	('Kassadin','Middle','Assassin','AP'),
	('Katarina','Middle','Assassin','AD'),
	('Kayle','Top','Specialist','AP'),
	('Kayn','Jungle','Skirmisher','AD'),
	('Kennen','Top','Specialist','AP'),
	('Kha''Zix','Jungle','Assassin','AD'),
	('Kindred','Jungle','Marksmen','AD'),
	('Kled','Top','Skirmisher','AD'),
	('Kog''Maw','Bottom','Marksmen','AD'),
	('K''Sante','Top','Warden/Skirmisher','AD'),
	('LeBlanc','Middle','Burst','AP'),
	('Lee Sin','Jungle','Diver','AD'),
	('Leona','Support','Vanguard','AD'),
	('Lillia','Jungle','Skirmisher','AP'),
	('Lissandra','Middle','Burst','AP'),
	('Lucian','Bottom','Marksmen','AD'),
	('Lulu','Support','Enchanter','AP'),
	('Lux','Support','Burst/Artillery','AP'),
	('Malphite','Top','Vanguard','AP'),
	('Malzahar','Middle','Battlemage','AP'),
	('Maokai','Support','Vanguard','AP'),
	('Master Yi','Jungle','Skirmisher','AD'),
	('Milio','Support','Enchanter','AP'),
	('Miss Fortune','Bottom','Marksmen','AD'),
	('Mordekaiser','Top','Juggernaut','AP'),
	('Morgana','Support','Catcher','AP'),
	('Naafiri','Middle','Assassin','AD'),
	('Nami','Support','Enchanter','AP'),
	('Nasus','Top','Juggernaut','Flex'),
	('Nautilus','Support','Vanguard','AD'),
	('Neeko','Middle','Burst/Catcher','AP'),
	('Nidalee','Jungle','Specialist','AP'),
	('Nilah','Bottom','Skirmisher','AD'),
	('Nocturne','Jungle','Assassin','AD'),
	('Nunu & Willump','Jungle','Vanguard','AP'),
	('Olaf','Top','Diver','AD'),
	('Orianna','Middle','Burst','AP'),
	('Ornn','Top','Vanguard','AD'),
	('Pantheon','Middle','Diver','AD'),
	('Poppy','Top','Warden','AD'),
	('Pyke','Support','Assassin/Catcher','AD'),
	('Qiyana','Middle','Assassin','AD'),
	('Quinn','Top','Specialist','AD'),
	('Rakan','Support','Catcher','AP'),
	('Rammus','Jungle','Vanguard','AD'),
	('Rek''Sai','Jungle','Diver','AD'),
	('Rell','Support','Vanguard','AD'),
	('Renata Glasc','Support','Enchanter','AP'),
	('Renekton','Top','Diver','AD'),
	('Rengar','Jungle','Assassin/Diver','Flex'),
	('Riven','Top','Skirmisher','AD'),
	('Rumble','Top','Battlemage','AP'),
	('Ryze','Middle','Battlemage','AP'),
	('Samira','Bottom','Marksmen','AD'),
	('Sejuani','Jungle','Vanguard','AD'),
	('Senna','Support','Marksmen/Enchanter','AD'),
	('Seraphine','Middle','Burst/Enchanter','AP'),
	('Sett','Top','Juggernaut','AD'),
	('Shaco','Jungle','Assassin','Flex'),
	('Shen','Top','Warden','AD'),
	('Shyvana','Jungle','Juggernaut','AD'),
	('Singed','Top','Specialist','AP'),
	('Sion','Top','Vanguard','AD'),
	('Sivir','Bottom','Marksmen','AD'),
	('Skarner','Jungle','Diver','AD'),
	('Smolder','Bottom','Marksmen','AD'),
	('Sona','Support','Enchanter','AP'),
	('Soraka','Support','Enchanter','AP'),
	('Swain','Middle','Battlemage','AP'),
	('Sylas','Middle','Burst/Skirmisher','AP'),
	('Syndra','Middle','Burst','AP'),
	('Tahm Kench','Top','Warden','AP'),
	('Taliyah','Jungle','Battlemage','AP'),
	('Talon','Middle','Assassin','AD'),
	('Taric','Support','Enchanter/Warden','AP'),
	('Teemo','Top','Specialist','AP'),
	('Thresh','Support','Catcher','AP'),
	('Tristana','Bottom','Marksmen','AD'),
	('Trundle','Top','Juggernaut','AD'),
	('Tryndamere','Top','Skirmisher','AD'),
	('Twisted Fate','Middle','Burst','Flex'),
	('Twitch','Bottom','Marksmen','Flex'),
	('Udyr','Top','Juggernaut','AD'),
	('Urgot','Top','Juggernaut','AD'),
	('Varus','Bottom','Marksmen','AD'),
	('Vayne','Bottom','Marksmen','AD'),
	('Veigar','Middle','Burst','AP'),
	('Vel''Koz','Middle','Artillery','AP'),
	('Vex','Middle','Burst','AP'),
	('Vi','Jungle','Diver','AD'),
	('Viego','Jungle','Skirmisher','AD'),
	('Viktor','Middle','Battlemage','AP'),
	('Vladimir','Middle','Battlemage','AP'),
	('Volibear','Top','Juggernaut','AP'),
	('Warwick','Jungle','Diver','AD'),
	('Wukong','Jungle','Diver','AD'),
	('Xayah','Bottom','Marksmen','AD'),
	('Xerath','Middle','Artillery','AP'),
	('Xin Zhao','Jungle','Diver','AD'),
	('Yasuo','Middle','Skirmisher','AD'),
	('Yone','Middle','Skirmisher/Assassin','AD'),
	('Yorick','Top','Juggernaut','AD'),
	('Yuumi','Support','Enchanter','AP'),
	('Zac','Jungle','Vanguard','AD'),
	('Zed','Middle','Assassin','AP'),
	('Zeri','Bottom','Marksmen','AD'),
	('Ziggs','Middle','Artillery','AP'),
	('Zilean','Support','Specialist','AP'),
	('Zoe','Middle','Burst','AP'),
	('Zyra','Support','Catcher','AP');


-- Showing Table(s)
SELECT * FROM SupportBottomPairing;
SELECT * FROM ChampionList;

-- debugger
SHOW DATABASES;